name: HubSpokeV2
env:
  subscriptionId: ${{ secrets.SUB_SANDBOX_3 }}
  azureRegion: East US 2
  templateFile: ./Azure-HubSpoke-v2/main.bicep
  parametersFile: ./Azure-HubSpoke-v2/main.parameters.jsonc

# Controls when the workflow will run
on:
  # Workflow will run on upon a commit
  push:
    branches:
      - main
    paths:
      - "Azure-HubSpoke-v2/**.bicep"
      - "Azure-HubSpoke-v2/**.jsonc"

  # Workflow can be triggered manually from the Actions tab
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to Azure using OIDC
        uses: Azure/login@v1
        with:          
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ env.subscriptionId }}
      
      - name: Deploy bicep file
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          deploymentName: 'Github.Actions-${{ github.workflow }}-${{ github.run_number }}'
          subscriptionId: ${{ env.subscriptionId }}
          region: ${{ env.azureRegion }}
          template: ${{ env.templateFile }}
          parameters: ${{ env.parametersFile}}